apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/WaailRajpoot/Istio-practise.git'
    targetRevision: '1.23.2'
    path: './gateway'
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
